### ISSUE TITLE
Use Bootstrap 4 beta

### ISSUE THREAD

**Issue by peterblazejewicz** [frederikprijck/angularjs-webpack-starter#5]
Just wanted to discuss migration to BS 4. 
We are using BS4 in the project(s) with NG1.*.
The migration to BS4 would make some things easier (Sass support, better customization), some will require additional changes: the BS4 ships without built-in icons. There are many possible solutions here, including FontAwesome 4.*  Sass dependency or using Google's Material Design Icons.

Sample migrated to BS4 with MD icons:
![image](https://user-images.githubusercontent.com/14539/30035936-6ac4e7a0-91af-11e7-941c-55cab03cfbcc.png)
![image](https://user-images.githubusercontent.com/14539/30035982-91844fe8-91af-11e7-8a56-031d5ff890fe.png)

Thanks!

**Comment by frederikprijck** [comment]
Using bootstrap 4 would mean u can't leverage `ui-bootstrap`, as that's for bootstrap 3.x.

I guess as long as u can live with that, moving to bootstrap 4 sounds reasonable.

**Comment by peterblazejewicz** [comment]
> Using bootstrap 4 would mean u can't leverage ui-bootstrap, as that's for bootstrap 3.x.

I understand, never though that way (we are not using ui-bootstrap/ng-bootstrap internally). Up to you Frederik.

**Comment by frederikprijck** [comment]
I guess UI-Bootstrap will continue to make use of Bootstrap 3.x for a while (I'd even doubt it's going to change in the future due to the existence of Angular).


People who are familiar enough with AngularJS to create their own directives for Bootstrap 4 will probably be familiar enough with AngularJS to not have any need for this starter. So I'd prefer to leave Bootstrap 4 out of this starter.
